name: go tidy

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/go.tidy.yml'
      - 'dlredirector/go.*'

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Tidy
        run: |
          cd dlredirector
          rm -f go.sum
          go mod tidy
          cd ..
      -
        name: Set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "auto-go-mod-tidy[bot]"
          git config user.email "auto-go-mod-tidy[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      -
        name: Commit and push changes
        run: |
          cd dlredirector
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m 'auto go mod tidy'
            git push
          fi
