name: Go

on: 
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/go.yml'
      - 'dlredirector/*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd dlredirector
        env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o linux-amd64/dlredirector -ldflags="-s -w" . && cp -r templates Corefile.tmpl linux-amd64/
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build -o linux-arm-5/dlredirector -ldflags="-s -w" . && cp -r templates Corefile.tmpl linux-arm-5/
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -o linux-arm-6/dlredirector -ldflags="-s -w" . && cp -r templates Corefile.tmpl linux-arm-6/
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o linux-arm-7/dlredirector -ldflags="-s -w" . && cp -r templates Corefile.tmpl linux-arm-7/
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o linux-arm64/dlredirector -ldflags="-s -w" . && cp -r templates Corefile.tmpl linux-arm64/
        env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o darwin-amd64/dlredirector -ldflags="-s -w" . && cp -r templates Corefile.tmpl darwin-amd64/
        env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o windows-amd64/dlredirector.exe -ldflags="-s -w" . && cp -r templates Corefile.tmpl windows-amd64/
        env CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -o freebsd-amd64/dlredirector -ldflags="-s -w" . && cp -r templates Corefile.tmpl freebsd-amd64/
        env CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 go build -o openbsd-amd64/dlredirector -ldflags="-s -w" . && cp -r templates Corefile.tmpl openbsd-amd64/
        env CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 go build -o netbsd-amd64/dlredirector -ldflags="-s -w" . && cp -r templates Corefile.tmpl netbsd-amd64/
        env CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 go build -o dragonfly-amd64/dlredirector -ldflags="-s -w" . && cp -r templates Corefile.tmpl dragonfly-amd64/
        cd ..
        env GOPATH=$PWD/gopath go install github.com/missdeer/cicdutil@latest
      
    - name: Upload artifact dlredirector-linux-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dlredirector-linux-amd64
        # Directory containing files to upload
        path: dlredirector/linux-amd64

    - name: Upload artifact dlredirector-linux-arm-5
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dlredirector-linux-arm-5
        # Directory containing files to upload
        path: dlredirector/linux-arm-5

    - name: Upload artifact dlredirector-linux-arm-6
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dlredirector-linux-arm-6
        # Directory containing files to upload
        path: dlredirector/linux-arm-6

    - name: Upload artifact dlredirector-linux-arm-7
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dlredirector-linux-arm-7
        # Directory containing files to upload
        path: dlredirector/linux-arm-7

    - name: Upload artifact dlredirector-linux-arm64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dlredirector-linux-arm64
        # Directory containing files to upload
        path: dlredirector/linux-arm64

    - name: Upload artifact dlredirector-darwin-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dlredirector-darwin-amd64
        # Directory containing files to upload
        path: dlredirector/darwin-amd64

    - name: Upload artifact dlredirector-dragonfly-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dlredirector-dragonfly-amd64
        # Directory containing files to upload
        path: dlredirector/dragonfly-amd64

    - name: Upload artifact dlredirector-openbsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dlredirector-openbsd-amd64
        # Directory containing files to upload
        path: dlredirector/openbsd-amd64

    - name: Upload artifact dlredirector-netbsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dlredirector-netbsd-amd64
        # Directory containing files to upload
        path: dlredirector/netbsd-amd64

    - name: Upload artifact dlredirector-freebsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dlredirector-freebsd-amd64
        # Directory containing files to upload
        path: dlredirector/freebsd-amd64

    - name: Upload artifact dlredirector-windows-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dlredirector-windows-amd64
        # Directory containing files to upload
        path: dlredirector/windows-amd64

    - name: Remove old artifacts
      run: |
        gopath/bin/cicdutil -p github -u missdeer -t ${{ secrets.GH_TOKEN }} -r coredns_custom_build -k 0 -a delete
